name: "Notify Action"
description: "Send an email notification using SMTP"
inputs:
  subject:
    description: "The subject of the email"
    required: true
  body:
    description: "The body of the email"
    required: true
  SMTP_USERNAME:
    description: "SMTP username for authentication"
    required: true
  SMTP_PASSWORD:
    description: "SMTP password for authentication"
    required: true
  NOTIFICATION_EMAIL:
    description: "Recipient email address"
    required: true
runs:
  using: "composite"
  steps:
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ inputs.SMTP_USERNAME }}
        password: ${{ inputs.SMTP_PASSWORD }}
        subject: "${{ inputs.subject }}"
        body: "${{ inputs.body }}"
        to: ${{ inputs.NOTIFICATION_EMAIL }}
        from: Web3Gateway