name: Notify
on:
  workflow_call:
    inputs:
      subject:
        required: true
        type: string
      body:
        required: true
        type: string
    secrets:
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      NOTIFICATION_EMAIL:
        required: true
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "${{ inputs.subject }}"
          body: "${{ inputs.body }}"
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: Web3Gateway